spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cn_jwt_assignment
    username: root
    password: Ram@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
okta:
  oauth2:
    issuer: https://dev-40397604.okta.com/oauth2/default
    client-id: 0oafsy42nwzXrMVcb5d7
    client-secret: eomZq1nfXxcsuHbjfQdaARWVgrafhfKPUJkp4dkwB0xoeQYycH0LNUEjDPyiShv1 

server:
  port: 8081